---
title: "2020 RECS Graphs"
output: html_document
date: "2024-01-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages}

library(tidyverse)
library(extrafont)
library(formattable)
loadfonts(device = "win")

```

```{r dataframes}

house_age <- data.frame(year_of_construction = c("<1950", "1950s", "1960s", "1970s", "1980s", "1990s", "2000s", "2010-15", "2016-20"),
           home_insecurity_perc = c(0.294, 0.296, 0.307, 0.299, 0.277, 0.238, 0.223, 0.242, 0.21))

insulation <- data.frame(insulation_type = c("Well-Insulated", "Adequately Insulated", "Poorly Insulated", "No Insulation"),
           insulation_households_n = c(34.34, 64.27, 21.29, 3.63),
           insecurity_households_n = c(6.58, 15.34, 9.8, 1.85),
           home_insecurity_perc = c(0.192, 0.239, 0.46, 0.51),
           legend_column = "Share of Energy Insecure Households", "Share of Energy Insecure Households", "Share of Energy Insecure Households", "Share of Energy Insecure Households")

race1 <- data.frame(race_cat = c("Total", "White"),
           insulation_households_n = c(123.53, 99.99),
           insecurity_households_n = c(33.58, 23.17),
           home_insecurity_perc = c(0.271, 0.232),
           se = c(0.005, 0.0039),
           legend_column = "Share of Energy Insecure Households", "Share of Energy Insecure Households")

race2 <- data.frame(race_cat = c("Black", "Hispanic", "Asian", "AI/AN"),
           insulation_households_n = c(12.67, 12.95, 6.06, 1.08),
           insecurity_households_n = c(5.87, 6.73, 1.53, 0.56),
           home_insecurity_perc = c(0.463, 0.52, 0.252, 0.519),
           se = c(0.0013, 0.0008, 0.0022, 0.001),
           legend_column = "Share of Energy Insecure Households", "Share of Energy Insecure Households", "Share of Energy Insecure Households", "Share of Energy Insecure Households")

income <- data.frame(inc_cat = c("$19,999 or less", "$20,000-$39,999", "$40,000-$59,999", "$60,000-$99,999", "$100,000+"),
           home_insecurity_perc = c(0.515, 0.397, 0.293, 0.201, 0.092))

```


```{r graphs}

##age

ggplot(house_age, aes(x = factor(year_of_construction, level = c("<1950", "1950s", "1960s", "1970s", "1980s", "1990s", "2000s", "2010-15", "2016-20")), y = home_insecurity_perc, label = scales::percent(home_insecurity_perc, accuracy = 0.1))) +
  geom_point(color = "#439381", size = 3) +
  geom_text(position = position_dodge(width = 0.9),
            vjust = 3,
            size = 4,
            color = "#439381",
            fontface = "bold",
            family = "Georgia") +
  labs(title = "\nPercent of Households Facing Energy Insecurity vs.\nDecade Home was Constructed (2020)",
       subtitle = "Individuals and families who live in older homes are more likely to experience energy insecurity.",
       caption = "\nJulia Tache | Analysis of RECS Survey Data (2020)") +
  ylab("Percent Positive") +
  scale_y_continuous(limits = c(0.19, 0.32), labels = scales::percent) +
  theme(plot.background = element_rect(fill = "#F5F5F5"),
        plot.title = element_text(face = "bold", size = 16),
        plot.subtitle = element_text(size = 12),
        plot.caption = element_text(size = 12, face = "italic"),
        axis.title.x = element_blank(),
        axis.text.x = element_text(color = "black", size = 11),
        axis.title.y = element_blank(),
        axis.text.y = element_text(face = "bold", color = "black", size = 11),
        legend.position = "none",
        text = element_text(family = "Georgia"))

ggsave("house_age.png", height = 5, width = 8)

##insulation

ggplot(insulation, aes(x = factor(insulation_type, level = c("Well-Insulated", "Adequately Insulated", "Poorly Insulated", "No Insulation")), y = insecurity_households_n, fill = legend_column)) +
  geom_bar(aes(y = insulation_households_n), stat = "identity", size = 1, color = "#e4fde1", fill = "#e4fde1", alpha = 0.5) +
  geom_bar(aes(fill = legend_column), stat = "identity") +
  scale_fill_manual(values = c("#439381")) +
  geom_text(aes(x = factor(insulation_type, level = c("Well-Insulated", "Adequately Insulated", "Poorly Insulated", "No Insulation")),
                           y = insecurity_households_n,
                           label = scales::percent(home_insecurity_perc, accuracy = 0.1)),
            position = position_dodge(width = 0.9),
            size = 3.25,
            vjust = 1.75,
            color = "black",
            fontface = "bold",
            family = "Georgia") +
    geom_text(aes(x = factor(insulation_type, level = c("Well-Insulated", "Adequately Insulated", "Poorly Insulated", "No Insulation")),
                           y = insulation_households_n,
                           label = paste0(insulation_households_n, "m")),
            position = position_dodge(width = 0.9),
            size = 4,
            vjust = -0.9,
            color = "black",
            fontface = "bold",
            family = "Georgia") +
  ylim(0, 70) +
  labs(title = "\nHousehold Level of Insulation: National Snapshot (2020)",
       subtitle = "Most Americans surveyed live in households with adequate insulation.\nProper insulation and weatherization play a huge role in ensuring\nefficient home heating and cooling.",
       caption = "\nJulia Tache | Analysis of RECS Survey Data (2020)") +
  ylab("Number of Housing Units (millions)") +
  theme(plot.background = element_rect(fill = "#F5F5F5"),
        plot.title = element_text(face = "bold", size = 16),
        plot.subtitle = element_text(size = 12),
        plot.caption = element_text (size = 12, face = "italic"),
        axis.title.x = element_blank(),
        axis.text.x = element_text(color = "black", size = 10),
        axis.title.y = element_text(size = 11),
        axis.text.y = element_text(face = "bold", color = "black", size = 11),
        legend.position = "top",
        legend.background = element_rect(fill = "#F5F5F5"),
        legend.title = element_blank(),
        legend.text = element_text(size = 10, face = "italic"),
        text = element_text(family = "Georgia"))

ggsave("insulation.png", height = 5, width = 8)

## race

ggplot(race1, aes(x = factor(race_cat, level = c("White", "Total")), y = insecurity_households_n, fill = legend_column)) +
  geom_bar(aes(y = insulation_households_n), stat = "identity", size = 1, color = "#e4fde1", fill = "#e4fde1", alpha = 0.5) +
  geom_bar(aes(fill = legend_column), stat = "identity") +
  scale_fill_manual(values = c("#439381")) +
  geom_text(aes(x = factor(race_cat, level = c("White", "Total")),
                           y = insecurity_households_n,
                           label = scales::percent(home_insecurity_perc, accuracy = 0.1)),
            position = position_dodge(width = 0.9),
            hjust = 1.25,
            size = 5,
            color = "black",
            fontface = "bold",
            family = "Georgia") +
    geom_text(aes(x = factor(race_cat, level = c("White", "Total")),
                           y = insulation_households_n,
                           label = paste0(insulation_households_n, "m")),
            position = position_dodge(width = 0.9),
            size = 5,
            hjust = -0.1,
            color = "black",
            fontface = "bold",
            family = "Georgia") +
  coord_flip() +
  labs(title = "\nPercent of Households Experiencing Energy Insecurity\n(Total vs. White Households) (2020)",
       subtitle = "Estimates from the Residential Energy Consumption Survey (RECS)",
       caption = "\nJulia Tache | Analysis of RECS Survey Data (2020)") +
  ylab("Number of Housing Units (millions)") +
  ylim(0, 150) +
  theme(plot.background = element_rect(fill = "#F5F5F5"),
        plot.title = element_text(face = "bold", size = 16, hjust = 0.5),
        plot.subtitle = element_text(size = 12, hjust = 0.5),
        plot.caption = element_text (size = 12, face = "italic"),
        axis.title.x = element_text(size = 11),
        axis.text.x = element_text(color = "black", size = 11),
        axis.title.y = element_blank(),
        axis.text.y = element_text(face = "bold", color = "black", size = 11),
        legend.position = "top",
        legend.background = element_rect(fill = "#F5F5F5"),
        legend.title = element_blank(),
        legend.text = element_text(size = 10, face = "italic"),
        text = element_text(family = "Georgia"))

ggsave("race1.png", height = 5, width = 8)

ggplot(race2, aes(x = factor(race_cat, level = c("AI/AN", "Asian", "Black", "Hispanic")), y = insecurity_households_n, fill = legend_column)) +
  geom_bar(aes(y = insulation_households_n), stat = "identity", size = 1, color = "#e4fde1", fill = "#e4fde1", alpha = 0.5) +
  geom_bar(aes(fill = legend_column), stat = "identity") +
  scale_fill_manual(values = c("#439381")) +
  geom_text(aes(x = factor(race_cat, level = c("AI/AN", "Asian", "Black", "Hispanic")),
                           y = insecurity_households_n,
                           label = scales::percent(home_insecurity_perc, accuracy = 0.1)),
            position = position_dodge(width = 0.9),
            hjust = 1,
            size = 4,
            color = "black",
            fontface = "bold",
            family = "Georgia") +
    geom_text(aes(x = factor(race_cat, level = c("AI/AN", "Asian", "Black", "Hispanic")),
                           y = insulation_households_n,
                           label = paste0(insulation_households_n, "m")),
            position = position_dodge(width = 0.9),
            size = 4,
            hjust = -0.01,
            color = "black",
            fontface = "bold",
            family = "Georgia") +
  coord_flip() +
  ylim(0, 15) +
  labs(title = "\nPercent of Households Experiencing Energy\nInsecurity by Race (2020)",
       subtitle = "Nearly half of Hispanic, Black, and American Indian/Alaska Native\n(AI/AN) households experience some level of energy insecurity.\nEstimates from the Residential Energy Consumption Survey (RECS)",
       caption = "\nJulia Tache | Analysis of RECS Survey Data (2020)") +
  ylab("Number of Housing Units (millions)") +
  theme(plot.background = element_rect(fill = "#F5F5F5"),
        plot.title = element_text(face = "bold", size = 16, hjust = 0.5),
        plot.subtitle = element_text(size = 12, hjust = 0.5),
        plot.caption = element_text (size = 12, face = "italic"),
        axis.title.x = element_text(size = 11),
        axis.text.x = element_text(color = "black", size = 11),
        axis.title.y = element_blank(),
        axis.text.y = element_text(face = "bold", color = "black", size = 11),
        legend.position = "top",
        legend.background = element_rect(fill = "#F5F5F5"),
        legend.title = element_blank(),
        legend.text = element_text(size = 10, face = "italic"),
        text = element_text(family = "Georgia"))

ggsave("race2.png", height = 5, width = 8)

##income

ggplot(income, aes(x = factor(inc_cat, level = c("$19,999 or less", "$20,000-$39,999", "$40,000-$59,999", "$60,000-$99,999", "$100,000+")), y = home_insecurity_perc)) +
  geom_bar(stat = "identity", color = "#439381", fill = "#439381") +
  geom_text(aes(label = scales::percent(home_insecurity_perc, accuracy = 0.1)),
            size = 6,
            vjust = 1.5,
            color = "black",
            fontface = "bold",
            family = "Georgia") +
  labs(title = "\nPercent of Households Experiencing\nEnergy Insecurity by Income (2020)\n",
       caption = "\nJulia Tache | Analysis of RECS Survey Data (2020)") +
  theme(plot.background = element_rect(fill = "#F5F5F5"),
        panel.background = element_rect(fill = "#F5F5F5"),
        panel.grid = element_blank(),
        plot.title = element_text(face = "bold", size = 18, hjust = 0.5),
        plot.subtitle = element_text(size = 12, hjust = 0.5),
        plot.caption = element_text (size = 12, face = "italic"),
        axis.title = element_blank(),
        axis.text.x = element_text(size = 11),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        text = element_text(family = "Georgia"))

ggsave("income.png", height = 5, width = 8)

```
